# Configuration file for proposal-gen-v1.py

# OpenAI API Key (REQUIRED)
# Obtain an API key from OpenRouter (https://openrouter.ai) and set it as an environment variable:
#   export OPENROUTER_API_KEY=your_api_key
# Or, you can paste your key directly below (not recommended for production):
#openai_api_key: ""

# OpenRouter API Base URL
openrouter_base_url: "https://openrouter.ai/api/v1"

# LLM Model
llm_model: "google/gemini-2.0-flash-001"

# Number of hypotheses to generate
num_hypotheses: 3

# Elo K-factor
elo_k_factor: 32

# Top K hypotheses for evolution
top_k_hypotheses: 2

# Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
logging_level: "INFO"

# Base log file name (without extension)
log_file_name: "app"

# FastAPI host
fastapi_host: "0.0.0.0"

# FastAPI port
fastapi_port: 8000
